### ISSUE TITLE
/eods_left slash command should get the current users who haven't submitted their EOD's

### ISSUE THREAD

**Issue by naiuhz** [Seneca-CDOT/Osteppy#19]
/eods_left slash command should read the current users (sleepy RA's) who haven't submitted their EOD's.

So /eods_left need to read the sleepyRAs.txt file.

This bug only occurs when the sleepyRAs.txt is manually edited.

**Comment by manekenpix** [comment]
Closed because this doesn't apply to the new version of osteppy. PR #77
