### ISSUE TITLE
Printed JSON should be user friendly formatted

### ISSUE THREAD

**Issue by naiuhz** [Seneca-CDOT/Osteppy#20]
Slash commands such as /add_eod_reminder should print user friendly formatted messages.

Eg. You've added this EOD reminder at 9:30PM for Monday's, Tuesday's, and Thursday's: "It's 9:30PM sleepy head, time to do your EOD!"

**Comment by naiuhz** [comment]
Also return the entire slash command the user entered in case they entered a typo or want to use it again for another EOD.

**Comment by manekenpix** [comment]
Closed because this doesn't apply to the new version of osteppy. PR #77
