### ISSUE TITLE
Optimize EODReminder.js

### ISSUE THREAD

**Issue by naiuhz** [Seneca-CDOT/Osteppy#27]
EODReminder.js' sendNextReminder loops through every RA and their reminders twice.
Instead, it should push reminders to the nextReminders array in the first loop and reset the array if a 
"sooner" reminder is found.

**Comment by naiuhz** [comment]
EODReminder might also send the earliest reminder on the first day of a holiday.

**Comment by manekenpix** [comment]
Closed because this doesn't apply to the new version of osteppy. PR #77
