### ISSUE TITLE
Create config files if they don't exist

### ISSUE THREAD

**Issue by naiuhz** [Seneca-CDOT/Osteppy#28]
During installation, there maybe config-files missing. Instead of errors, the necessary config-files should be created.
Config-files used:

- channelID.json
- EODReminderTimes.json
- eods.json
- RAs.txt
- SLACK_TOKEN
- sleepyRAs.txt

**Comment by naiuhz** [comment]
/set_eod_reminder_channel should add slack user to RAs.txt and sleepyRAs.txt if user name doesn't exist

**Comment by manekenpix** [comment]
Closed because this doesn't apply to the new version of osteppy. PR #77
