### ISSUE TITLE
Create single installation script

### ISSUE THREAD

**Issue by naiuhz** [Seneca-CDOT/Osteppy#32]
Osteppy needs a single installation script which also detects which OS the system is on.

**Comment by naiuhz** [comment]
1. Auto detect OS and ask if user would like to process to install in service directory (eg. Fedora uses /usr/lib/systemd/system/)
2. If OS is not detected, ask user to input service directory and which command to reload, enable, start and restart the service manager.

**Comment by manekenpix** [comment]
Closed because this doesn't apply to the new version of osteppy. PR #77
